blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/redis/go-redis-entraid/blob/main/README.md
    about: Check if your issue is already addressed in the documentation.
  - name: go-redis repository
    url: https://github.com/redis/go-redis
    about: For issues related to the Redis client itself, please file an issue in the go-redis repository.

